version: '3.3'

services:
    resources:
        image: python:3.8-buster
        command: 
            python /usr/src/app/app.py start_server --ports=9292
        volumes:
            - .:/usr/src/app
        ports:
            - "9292:9292"
        depends_on: 
            - neo4j

    neo4j:
        image: neo4j:3.5.7
        ports:
            - '7474:7474'
            - '7473:7473'
            - '7687:7687'
        expose:
            - 7474
        environment: 
            - NEO4J_AUTH=neo4j/tenant
            - NEO4JLABS_PLUGINS=["apoc"]
        volumes:
            # - "./configs/neo4j/data:/data"
            # - "./configs/neo4j/conf:/conf"
            - "./configs/neo4j/plugins:/plugins"
            # - "./configs/neo4j/import:/import"
            # - "./configs/neo4j/logs:/logs"
